openapi: 3.0.0
info:
  title: Contacts API
  version: 1.0.0
paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        '200':
          description: A list of contacts
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                favoriteColor:
                  type: string
                birthday:
                  type: string
      responses:
        '201':
          description: Contact created
  /contacts/{id}:
    get:
      summary: Get a single contact by ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      responses:
        '200':
          description: A single contact
    put:
      summary: Update a contact
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '204':
          description: Contact updated
    delete:
      summary: Delete a contact
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Contact deleted
